import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainLayout from "../components/layouts/MainLayout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { QueryClientProvider } from "react-query";
import { queryClient } from "../utils/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: {
    locale: string;
  };
}>) {
  const message = await getMessages({ locale });
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={message}>
          <MainLayout> {children}</MainLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
